serverKeys:
  encryptionKey: oFkFf4pO4zhQym4Z1iVQyF5W+R2zq+fo4arLenC+OKg=
  hashingKey: SEHumXZLSTWvjZOUvj5PDKffwb+fBxC/RTBNlUCescaLO3pegmjX493YeA6J8rijF23GoV2Yp7M3VS0EbLY46Q==

jwt:
  secret: oncxi1uiFfy+kHTh59N5jZpPKVGL+z71xq2z+/oSlYE=

db:
  host: localhost
  port: 5432
  name: acloud-test
  user: acloud
  password: acloud123

s3:
  are_local_buckets: false
  use_path_style_urls: true
  b2-eu-cen:
    key:
    secret:
    endpoint: https://s3.us-west-000.backblazeb2.com
    region: us-west-000
    bucket: acloud

endpoint:
  api: "http://localhost:3000"

internal:
  disableRegistration: false
