services:
  postgres_a_cloud:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_a_cloud_data:/var/lib/postgresql/data

volumes:
  postgres_a_cloud_data: {}
